describe('Portfolio Optimization Tests', () => {
  beforeEach(() => {
    cy.visit('https://www.portfoliovisualizer.com/optimize-portfolio')
  })

  it('TC-PO01: Valid optimization result', () => {
    cy.get('#mode').select('2')
    cy.get('#timePeriod').select('4')
    cy.get('#startYear').select('2000')
    cy.get('#endYear').select('2020')
    cy.get('#goal').select('2')
    cy.get('#robustOptimization').select('false')
    cy.get('#historicalReturns').select('true')
    cy.get('#constrained').select('true')
    cy.get('#groupConstraints').select('false')
    cy.get('#comparedAllocation').select('-1')
    cy.get('#benchmark').select('')

    cy.get('#symbol1').clear().type('VTI')
    cy.get('#allocation1_1').clear().type('80')
    cy.get('#minWeight1').clear().type('0')
    cy.get('#maxWeight1').clear().type('100')

    cy.get('#symbol2').clear().type('GLD')
    cy.get('#allocation2_1').clear().type('20')
    cy.get('#minWeight2').clear().type('0')
    cy.get('#maxWeight2').clear().type('100')

    cy.get('#submitButton').click()
    cy.url().should('include', '#analysisResults')
  })

 it('TC-PO02: Valid, all toggles and boundaries', () => {
  cy.get('#mode').select('2')
  cy.get('#timePeriod').select('2')
  cy.get('#startYear').select('1985')
  cy.get('#firstMonth').select('1')
  cy.get('#endYear').select('2025')
  cy.get('#lastMonth').select('12')
  cy.get('#goal').select('3')
  cy.get('#targetAnnualReturn').clear().type('1')
  cy.get('#robustOptimization').select('true')
  cy.get('#historicalReturns').select('false')
  cy.get('#historicalVolatility').select('false')
  cy.get('#historicalCorrelations').select('false')
  
  // Upload the correlation matrix file
  cy.get('#correlationsFile').selectFile('cypress/fixtures/CorrelationMatrix (1).csv')
  
  cy.get('#constrained').select('true')
  cy.get('#groupConstraints').select('false')
  cy.get('#comparedAllocation').select('-1')

  cy.get('#symbol1').clear().type('VTI')
  cy.get('#allocation1_1').clear().type('0')
  cy.get('#mean1').clear().type('0.1')
  cy.get('#volatility1').clear().type('0.1')
  cy.get('#minWeight1').clear().type('0')
  cy.get('#maxWeight1').clear().type('100')

  cy.get('#symbol2').clear().type('SPY')
  cy.get('#allocation2_1').clear().type('100')
  cy.get('#mean2').clear().type('0.2')
  cy.get('#volatility2').clear().type('0.1')
  cy.get('#minWeight2').clear().type('0')
  cy.get('#maxWeight2').clear().type('100')

  cy.get('#submitButton').click()
  cy.url().should('include', '#analysisResults')
})

  it('TC-PO03: Success for all remaining valids', () => {
  cy.get('#mode').select('1')
  cy.wait(500)
  cy.get('#timePeriod').select('2')
  cy.get('#startYear').select('1988')
  cy.get('#firstMonth').select('12')
  cy.get('#endYear').select('2024')
  cy.get('#lastMonth').select('9')
  cy.get('#goal').select('16')
  cy.get('#targetTailLoss').clear().type('0.15')
  cy.get('#constrained').select('false')
  cy.get('#comparedAllocation').select('2')
  cy.get('#benchmark').select('VFINX')
  cy.get('#regimeType').select('Market Volatility')

  cy.get('#asset1').select('MidCapBlend')
  cy.get('#allocation1_1').clear().type('2')

  cy.get('#asset2').select('IntlDeveloped')
  cy.get('#allocation2_1').clear().type('98')

  cy.get('#submitButton').click()
  cy.url().should('include', '#analysisResults')
})

  it('TC-PO04: Error for invalid dates & symbols, allocation/weight invalids', () => {
    cy.get('#mode').select('2')
    cy.get('#timePeriod').select('4')
    cy.get('#startYear').select('2025')
    cy.get('#endYear').select('1985')
    cy.get('#goal').select('2')
    cy.get('#robustOptimization').select('false')
    cy.get('#historicalReturns').select('true')
    cy.get('#constrained').select('true')
    cy.get('#groupConstraints').select('false')
    cy.get('#comparedAllocation').select('-1')
    cy.get('#benchmark').select('VFINX')
    cy.get('#regimeType').select('Market Volatility')

    cy.get('#symbol1').clear().type('INVALID')
    cy.get('#allocation1_1').clear().type('-1')
    cy.get('#minWeight1').clear().type('60')
    cy.get('#maxWeight1').clear().type('50')

    cy.get('#symbol2').clear().type('INVALID2')
    cy.get('#allocation2_1').clear().type('101')
    cy.get('#minWeight2').clear().type('40')
    cy.get('#maxWeight2').clear().type('30')

    cy.get('#submitButton').click()

    cy.contains('Maximum weight for asset INVALID on row 1 must be greater than minimum weight').should('be.visible')
    cy.contains('Maximum weight for asset INVALID2 on row 2 must be greater than minimum weight').should('be.visible')
    cy.contains('Unknown symbol: INVALID').should('be.visible')
    cy.contains('Unknown symbol: INVALID2').should('be.visible')
    cy.contains('Start year must be before or equal to the end year').should('be.visible')
  })

  it('TC-PO05: Error for invalid ER/Vol', () => {
    cy.get('#mode').select('2')
    cy.get('#timePeriod').select('4')
    cy.get('#startYear').select('2008')
    cy.get('#endYear').select('2020')
    cy.get('#goal').select('2')
    cy.get('#robustOptimization').select('false')
    cy.get('#historicalReturns').select('false')
    cy.get('#historicalVolatility').select('false')
    cy.get('#historicalCorrelations').select('true')
    cy.get('#constrained').select('true')
    cy.get('#groupConstraints').select('false')
    cy.get('#comparedAllocation').select('2')

    cy.get('#symbol1').clear().type('VTSMX')
    cy.get('#allocation1_1').clear().type('1')
    cy.get('#mean1').clear().type('-5')
    cy.get('#volatility1').clear().type('-10')
    cy.get('#minWeight1').clear().type('60')
    cy.get('#maxWeight1').clear().type('50')

    cy.get('#symbol2').clear().type('VGTSX')
    cy.get('#allocation2_1').clear().type('98')
    cy.get('#mean2').clear().type('200')
    cy.get('#volatility2').clear().type('500')
    cy.get('#minWeight2').clear().type('40')
    cy.get('#maxWeight2').clear().type('30')

    cy.get('#symbol3').clear().type('EVFMX')
    cy.get('#allocation3_1').clear().type('1')
    cy.get('#minWeight3').clear().type('10')
    cy.get('#maxWeight3').clear().type('20')

    cy.get('#submitButton').click()

    cy.contains('Maximum weight for asset VTSMX on row 1 must be greater than minimum weight').should('be.visible')
    cy.contains('Maximum weight for asset VGTSX on row 2 must be greater than minimum weight').should('be.visible')
    cy.contains('Volatility for Vanguard Total Stock Mkt Idx Inv (VTSMX) cannot be negative').should('be.visible')
    cy.contains('No mean return specified for E-Valuator Moderate (50%-70%) RMS R4 (EVFMX)').should('be.visible')
    cy.contains('No volatility specified for E-Valuator Moderate (50%-70%) RMS R4 (EVFMX)').should('be.visible')
  })

  it('TC-PO06: Accepted, no errors', () => {
    cy.get('#mode').select('2')
    cy.get('#timePeriod').select('4')
    cy.get('#startYear').select('2006')
    cy.get('#endYear').select('2025')
    cy.get('#goal').select('2')
    cy.get('#robustOptimization').select('true')
    cy.get('#historicalReturns').select('false')
    cy.get('#historicalVolatility').select('false')
    cy.get('#historicalCorrelations').select('true')
    cy.get('#constrained').select('false')
    cy.get('#groupConstraints').select('false')
    cy.get('#comparedAllocation').select('2')

    cy.get('#symbol1').clear().type('VTI')
    cy.get('#allocation1_1').clear().type('40')
    cy.get('#mean1').clear().type('50')
    cy.get('#volatility1').clear().type('100')

    cy.get('#symbol2').clear().type('GLD')
    cy.get('#allocation2_1').clear().type('60')
    cy.get('#mean2').clear().type('45')
    cy.get('#volatility2').clear().type('100')

    cy.get('#submitButton').click()
    cy.url().should('include', '#analysisResults')
  })

  it('TC-PO07: Accepted, no errors', () => {
    cy.get('#mode').select('2')
    cy.get('#timePeriod').select('4')
    cy.get('#startYear').select('2006')
    cy.get('#endYear').select('2025')
    cy.get('#goal').select('2')
    cy.get('#robustOptimization').select('true')
    cy.get('#historicalReturns').select('false')
    cy.get('#historicalVolatility').select('false')
    cy.get('#historicalCorrelations').select('true')
    cy.get('#constrained').select('false')
    cy.get('#groupConstraints').select('false')
    cy.get('#comparedAllocation').select('2')

    cy.get('#symbol1').clear().type('VTI')
    cy.get('#allocation1_1').clear().type('40')
    cy.get('#mean1').clear().type('0.1')
    cy.get('#volatility1').clear().type('0.1')

    cy.get('#symbol2').clear().type('GLD')
    cy.get('#allocation2_1').clear().type('60')
    cy.get('#mean2').clear().type('0.2')
    cy.get('#volatility2').clear().type('0.2')

    cy.get('#submitButton').click()
    cy.url().should('include', '#analysisResults')
  })
})