describe('Tactical Asset Allocation Tests', () => {
  beforeEach(() => {
    cy.visit('https://www.portfoliovisualizer.com/tactical-asset-allocation-model')
  })

  it('TAA01: Success, default scenario', () => {
    cy.get('#timingModel').select('3')
    cy.get('#timePeriod').select('4')
    cy.get('#startYear').select('1985')
    cy.get('#endYear').select('2025')
    cy.get('#includeYTD').select('false')
    cy.get('#initialAmount').clear().type('10000')
    cy.get('#periodicAdjustment').select('0')
    cy.get('#symbol').clear().type('SPDR S&P 500 ETF (SPY)')
    cy.get('#outOfMarketAssetType').select('1')
    cy.get('#movingAverageSignal').select('1')
    cy.get('#movingAverageType').select('1')
    cy.get('#windowSize').select('8')
    cy.get('#stopLossMode').select('0')
    cy.get('#rebalancePeriod').select('1')
    cy.get('#separateSignalAsset').select('false')
    cy.get('#tradeExecution').select('0')
    cy.get('#leverageType').select('0')
    cy.get('#comparedAllocation').select('-1')
    cy.get('#benchmark').select('')

    cy.get('#submitButton').click()
    cy.url().should('include', '#analysisResults')
  })

  it('TAA02: Complex scenario accepted', () => {
    cy.get('#timingModel').select('4')
    cy.get('#timePeriod').select('4')
    cy.get('#startYear').select('2000')
    cy.get('#endYear').select('2020')
    cy.get('#initialAmount').clear().type('50000')
    cy.get('#periodicAdjustment').select('1')
    cy.get('#adjustmentAmount').clear().type('500')
    cy.get('#inflationAdjusted').select('true')
    cy.get('#adjustmentFrequency').select('4')
    cy.get('#symbols').clear().type('SPY, BND, GLD')
    cy.get('#multipleTimingPeriods').select('false')
    cy.get('#windowSize').select('12')
    cy.get('#excludePreviousMonth').select('false')
    cy.get('#assetsToHold').select('1')
    cy.get('#allocationWeights').select('0')
    cy.get('#riskControlType').select('2')
    cy.get('#riskWindowSize').select('-1')
    cy.get('#riskWindowSizeInDays').clear().type('5')
    cy.get('#riskWindowAsset').clear().type('SPDR S&P 500 ETF (SPY)')
    cy.get('#stopLossMode').select('1')
    cy.get('#stopLossThreshold').clear().type('5.0')
    cy.get('#stopLossAssetType').select('1')
    cy.get('#rebalancePeriod').select('0')
    cy.get('#tradeExecution').select('1')
    cy.get('#leverageType').select('0')
    cy.get('#comparedAllocation').select('-1')
    cy.get('#benchmark').select('VFINX')
    cy.get('#regimeType').select('')

    cy.get('#submitButton').click()
    cy.url().should('include', '#analysisResults')
  })

  it('TAA03: Proper error/validation', () => {
    cy.get('#timingModel').select('2')
    cy.get('#timePeriod').select('2')
    cy.get('#startYear').select('2025')
    cy.get('#firstMonth').select('1')
    cy.get('#endYear').select('1972')
    cy.get('#lastMonth').select('12')
    cy.get('#initialAmount').clear().type('0')
    cy.get('#periodicAdjustment').select('3')
    cy.get('#adjustmentPercentage').clear().type('101.1')
    cy.get('#adjustmentFrequency').select('4')
    cy.get('#leverageType').select('2')
    cy.get('#debtAmount').clear().type('3-500-200102123131231313')
    cy.get('#debtInterest').clear().type('-1332131')
    cy.get('#maintenanceMargin').clear().type('-2323232')
    cy.get('#leveragedBenchmark').select('true')
    cy.get('#comparedAllocation').select('-1')
    cy.get('#benchmark').select('VFINX')
    cy.get('#regimeType').select('')

    cy.get('#submitButton').click()

    cy.contains('The selected benchmark Vanguard 500 Index Investor (1977-2025) does not cover the selected year range (2025-1972)').should('exist')
    cy.contains('Start year must be before or equal to the end year').should('exist')
    cy.contains('Initial portfolio balance should be a positive integer').should('exist')
    cy.contains('Withdrawal percentage must be between 0% and 90%').should('exist')
  })

  it('TAA04: Advanced features accepted', () => {
    cy.get('#timingModel').select('7')
    cy.get('#timePeriod').select('4')
    cy.get('#startYear').select('2007')
    cy.get('#endYear').select('2022')
    cy.get('#initialAmount').clear().type('25000')
    cy.get('#periodicAdjustment').select('1')
    cy.get('#adjustmentAmount').clear().type('300')
    cy.get('#inflationAdjusted').select('true')
    cy.get('#adjustmentFrequency').select('4')
    cy.get('#volatilityTarget').clear().type('9.0')
    cy.get('#downsideVolatility').select('false')
    cy.get('#tradeExecution').select('0')
    cy.get('#leverageType').select('1')
    cy.get('#leverageRatio').clear().type('50.0')
    cy.get('#debtInterest').clear().type('5')
    cy.get('#leveragedBenchmark').select('true')
    cy.get('#comparedAllocation').select('0')
    cy.get('#benchmark').select('')

    cy.get('#symbol1').clear().type('SPDR S&P 500 ETF (SPY)')
    cy.get('#allocation1_1').clear().type('100')

    cy.get('#submitButton').click()
    cy.url().should('include', '#analysisResults')
  })

  it('TAA05: Custom/alternate features', () => {
    cy.get('#timingModel').select('3')
    cy.get('#timePeriod').select('2')
    cy.get('#startYear').select('1990')
    cy.get('#firstMonth').select('6')
    cy.get('#endYear').select('2015')
    cy.get('#lastMonth').select('6')
    cy.get('#calendarAligned').select('true')
    cy.get('#initialAmount').clear().type('1')
    cy.get('#periodicAdjustment').select('0')
    cy.get('#symbol').clear().type('Vanguard 500 Index Investor (VFINX)')
    cy.get('#outOfMarketAssetType').select('1')
    cy.get('#movingAverageSignal').select('1')
    cy.get('#movingAverageType').select('2')
    cy.get('#windowSize').select('10')
    cy.get('#stopLossMode').select('2')
    cy.get('#stopLossThreshold').clear().type('5.0')
    cy.get('#stopLossAssetType').select('1')
    cy.get('#rebalancePeriod').select('2')
    cy.get('#separateSignalAsset').select('false')
    cy.get('#tradeExecution').select('1')
    cy.get('#leverageType').select('0')
    cy.get('#comparedAllocation').select('-1')
    cy.get('#benchmark').select('')

    cy.get('#submitButton').click()
    cy.url().should('include', '#analysisResults')
  })

  it('TAA06: Min/lower values allowed', () => {
    cy.get('#timingModel').select('7')
    cy.get('#timePeriod').select('2')
    cy.get('#startYear').select('1972')
    cy.get('#firstMonth').select('6')
    cy.get('#endYear').select('2025')
    cy.get('#lastMonth').select('6')
    cy.get('#calendarAligned').select('true')
    cy.get('#initialAmount').clear().type('1')
    cy.get('#periodicAdjustment').select('3')
    cy.get('#adjustmentPercentage').clear().type('0.1')
    cy.get('#adjustmentFrequency').select('4')
    cy.get('#volatilityTarget').clear().type('0.1')
    cy.get('#downsideVolatility').select('false')
    cy.get('#tradeExecution').select('1')
    cy.get('#leverageType').select('1')
    cy.get('#leverageRatio').clear().type('0.1')
    cy.get('#debtInterest').clear().type('0.1')
    cy.get('#leveragedBenchmark').select('true')
    cy.get('#comparedAllocation').select('-1')
    cy.get('#benchmark').select('')

    cy.get('#symbol1').clear().type('SPDR S&P 500 ETF (SPY)')
    cy.get('#allocation1_1').clear().type('100')

    cy.get('#submitButton').click()
    cy.url().should('include', '#analysisResults')
  })

  it('TAA07: Maximum/upper values allowed', () => {
    cy.get('#timingModel').select('7')
    cy.get('#timePeriod').select('4')
    cy.get('#startYear').select('1972')
    cy.get('#endYear').select('2025')
    cy.get('#includeYTD').select('true')
    cy.get('#initialAmount').clear().type('9999999999999')
    cy.get('#periodicAdjustment').select('1')
    cy.get('#adjustmentAmount').clear().type('999999999999')
    cy.get('#inflationAdjusted').select('true')
    cy.get('#adjustmentFrequency').select('4')
    cy.get('#volatilityTarget').clear().type('50')
    cy.get('#downsideVolatility').select('false')
    cy.get('#tradeExecution').select('1')
    cy.get('#leverageType').select('1')
    cy.get('#leverageRatio').clear().type('100')
    cy.get('#debtInterest').clear().type('25')
    cy.get('#leveragedBenchmark').select('true')
    cy.get('#comparedAllocation').select('-1')
    cy.get('#benchmark').select('')

    cy.get('#symbol1').clear().type('SPDR S&P 500 ETF (SPY)')
    cy.get('#allocation1_1').clear().type('100')

    cy.get('#submitButton').click()
    cy.url().should('include', '#analysisResults')
  })
})